/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: Christian Rambow (https://sketchfab.com/art-3d.com)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/ibex-statue-scan-berlin-tierpark-0f274384b28044e3a29fd87e4c765238
title: Ibex Statue Scan - Berlin - Tierpark
*/

import * as THREE from 'three'
import React, {useRef} from 'react'
import {useLoader} from 'react-three-fiber'
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader'

function Ibex(props) {
    const group = useRef()
    const {nodes, materials} = useLoader(
        GLTFLoader,
        'https://dl.dropbox.com/s/x7loggfcqf5fpxt/ibex.glb?dl=0'
    )

    let r = '/textures/envmaps/bridge/'
    let urls = [
        r + 'posx.jpg',
        r + 'negx.jpg',
        r + 'posy.jpg',
        r + 'negy.jpg',
        r + 'posz.jpg',
        r + 'negz.jpg',
    ]

    const envMap = new THREE.CubeTextureLoader().load(urls)

    materials.DefaultMaterial.envMap = envMap
    materials.DefaultMaterial.envMapIntensity = 6.0

    // Rotate mesh every frame, this is outside of React without overhead
    // useFrame(() => (group.current.rotation.y += 0.01))

    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        material={materials.DefaultMaterial}
                        geometry={nodes.defaultMaterial.geometry}
                    />
                </group>
            </group>
        </group>
    )
}

export default Ibex
